# Generated by Django 3.2.5 on 2021-08-03 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('distance', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Tea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('details', models.TextField()),
                ('status', models.IntegerField(default=1)),
                ('picture', models.ImageField(blank=True, upload_to='tea/%Y%m%d/')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teas', to='mytea.store')),
            ],
        ),
    ]
