# Generated by Django 3.2.5 on 2021-08-03 09:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mytea', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oid', models.CharField(max_length=20)),
                ('total_price', models.FloatField(default=0)),
                ('status', models.BooleanField(default=False)),
                ('paied', models.BooleanField(default=False)),
                ('otime', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='mytea.store')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-otime',),
            },
        ),
        migrations.CreateModel(
            name='TeaAdd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TeaAdd_name', models.CharField(max_length=100)),
                ('TeaAdd_Tea', models.ManyToManyField(related_name='TeaAdd', to='mytea.Tea')),
            ],
        ),
        migrations.CreateModel(
            name='SingleOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sprice', models.FloatField(default=0)),
                ('num', models.IntegerField(default=0)),
                ('Order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='order.order')),
                ('tea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tea', to='mytea.tea')),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Option_name', models.CharField(max_length=100)),
                ('Option_price', models.FloatField(default=0)),
                ('Option_Single', models.ManyToManyField(related_name='Option', to='order.SingleOrder')),
                ('Option_TeaAdd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Option', to='order.teaadd')),
            ],
        ),
    ]
