# Generated by Django 3.2.5 on 2021-07-27 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mytea', '0001_initial'),
        ('order', '0002_order_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeaAdd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TeaAdd_name', models.CharField(max_length=100)),
                ('TeaAdd_Tea', models.ManyToManyField(related_name='TeaAdd', to='mytea.Tea')),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Option_name', models.CharField(max_length=100)),
                ('Option_Single', models.ManyToManyField(related_name='Option', to='order.SingleOrder')),
                ('Option_TeaAdd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Option', to='order.teaadd')),
            ],
        ),
    ]
