# Generated by Django 3.2.5 on 2021-07-29 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_option_teaadd'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='Option_price',
            field=models.FloatField(default=0),
        ),
    ]
