# Generated by Django 3.2.5 on 2021-07-30 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mytea', '0001_initial'),
        ('order', '0004_option_option_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-otime',)},
        ),
        migrations.AddField(
            model_name='order',
            name='store',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='mytea.store'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='singleorder',
            name='sprice',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
