# Generated by Django 3.2.5 on 2021-08-02 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_auto_20210730_2251'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paied',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='singleorder',
            name='sprice',
            field=models.FloatField(default=0),
        ),
    ]
